version: '3.1'
services:
  sonar-server:
    image: sonarqube:8.9.1-community
    build:
      context: .
      dockerfile: Dockerfile1
    ports:
      - 9000:9000

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli

    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - sonar-server
