# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  sonarqube: clicklogiq/sonarqube@1.0.1
 
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:      
      - sonarqube/analyze:
          SONARQUBE_SERVER_ORGANIZATION: 'Rocas Inc.'
          SONARQUBE_SERVER_URL: 'http://rocasinc.com:9000'
          SONARQUBE_SERVER_LOGIN: 'squ_99b453521d8104875d4e478ec486a7e14a44daa4'
          CIRCLE_PROJECT_REPONAME: 'my:project'

